# Generated by Django 3.0.8 on 2020-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20200719_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordrole',
            name='assign_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
