# Generated by Django 3.0.8 on 2020-07-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_discordrole_assign_by_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailrole",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
