# Generated by Django 3.0.8 on 2020-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0006_auto_20200720_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailrole",
            name="discord_roles",
            field=models.ManyToManyField(blank=True, to="registrations.DiscordRole"),
        ),
    ]
