"""
Django settings for discoreg project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False) == "1"

ALLOWED_HOSTS = [
    "pyohio-registration.herokuapp.com",
    "prod-pyohio-registration.herokuapp.com",
    "admin.pyohio.org",
    "chat.pyohio.org",
    "tylerdave.ngrok.io",
    "localhost",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "registrations",
    "nextupbot",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# MIDDLEWARE_CLASSES = [
#     "whitenoise.middleware.WhiteNoiseMiddleware",
# ]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "discoreg.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "discoreg.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)


SITE_ID = 1


if raygun_apikey := os.environ.get("RAYGUN_APIKEY"):
    MIDDLEWARE += ("raygun4py.middleware.django.Provider",)
    RAYGUN4PY_CONFIG = {
        "api_key": raygun_apikey,
    }


DISCORD_CLIENT_ID = os.environ["DISCORD_CLIENT_ID"]
DISCORD_CLIENT_SECRET = os.environ["DISCORD_CLIENT_SECRET"]
DISCORD_API_BASE_URL = "https://discord.com/api"
DISCORD_AUTHORIZATION_BASE_URL = f"{DISCORD_API_BASE_URL}/oauth2/authorize"
DISCORD_TOKEN_URL = f"{DISCORD_API_BASE_URL}/oauth2/token"
DISCORD_SCOPES = [
    "identify",
    "email",
    # "guilds",
    "guilds.join",
    # "connections",
]
DISCORD_GUILD_ID = os.environ["DISCORD_GUILD_ID"]
DISCORD_BOT_CHANNEL = int(os.environ.get("DISCORD_BOT_CHANNEL", "734788395024515153"))
DISCORD_BOT_DEBUG_CHANNEL = int(
    os.environ.get("DISCORD_BOT_DEBUG_CHANNEL", "734788395024515153")
)
DISCORD_BOT_EVENT_ROLE = int(
    os.environ.get("DISCORD_BOT_EVENT_ROLE", "1184735192418631700")
)

DISCORD_BOT_EVENT_START_DATETIME = os.environ.get(
    "DISCORD_BOT_EVENT_START_DATETIME", "2023-12-16T06:00:00-0500"
)
DISCORD_BOT_EVENT_END_DATETIME = os.environ.get(
    "DISCORD_BOT_EVENT_END_DATETIME", "2023-12-16T23:59:59-0500"
)
DISCORD_BOT_OFFSET_SECONDS = int(os.environ.get("DISCORD_BOT_OFFSET_SECONDS", "0"))
DISCORD_BOT_TOKEN = os.environ["DISCORD_BOT_TOKEN"]
DISCORD_BOT_WINDOW_SECONDS = int(os.environ.get("DISCORD_BOT_WINDOW_SECONDS", "30"))
TITO_WEBHOOK_TOKEN = os.environ["TITO_WEBHOOK_TOKEN"]

import django_heroku

django_heroku.settings(locals(), allowed_hosts=False)
